import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ActionIcon, Alert, Badge, Button, PasswordInput, Select, Textarea, TextInput } from '@mantine/core'
import { BarChart3, Check, FileText, LayoutDashboard, LogOut, Menu, MessageCircle, Plus, RefreshCw, Save, Send, Settings2, SlidersHorizontal, Trash2, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useForm } from 'react-hook-form'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { z } from 'zod'
import type { Comment, Content, NowStatus } from '@manifold/contracts'
import { clearSession, createAdminClient, readStoredSession, storeSession } from './api'
import { SettingsWorkspace } from './SettingsWorkspace'
import './App.css'

type View = 'dashboard' | 'content' | 'comments' | 'now' | 'settings'
type Session = { accessToken: string; username: string; expiresAt: number }

const loginSchema = z.object({ username: z.string().trim().min(1, 'Username is required.'), password: z.string().min(8, 'Password must be at least 8 characters.') })
const contentSchema = z.object({ kind: z.enum(['POST', 'NOTE', 'RESEARCH']), slug: z.string().trim().min(1, 'Slug is required.'), title: z.string().trim().min(1, 'Title is required.'), summary: z.string().max(4000), body: z.string().min(1, 'Body is required.'), tags: z.string() })
const nowSchema = z.object({ title: z.string().trim().min(1, 'Title is required.'), detail: z.string(), mood: z.string().min(1, 'Mood is required.') })
type ContentForm = z.infer<typeof contentSchema>
type LoginForm = z.infer<typeof loginSchema>
type NowForm = z.infer<typeof nowSchema>

function LoginScreen({ onLogin }: { onLogin: (session: Session) => void }) {
  const form = useForm<LoginForm>({ resolver: zodResolver(loginSchema), defaultValues: { username: 'admin', password: '' } })
  const mutation = useMutation({ mutationFn: (input: LoginForm) => createAdminClient().login(input), onSuccess: (result, input) => onLogin(storeSession({ ...result, username: input.username })) })
  return <main className="login-shell"><section className="login-panel"><div className="brand-mark">manifold<span>.</span></div><p className="kicker">Private workspace</p><h1>Make the garden legible.</h1><p className="login-copy">Manage the stream, review conversations, and keep the present moment current.</p><form onSubmit={form.handleSubmit((input) => mutation.mutate(input))} className="form-stack"><TextInput label="Username" {...form.register('username')} autoComplete="username" error={form.formState.errors.username?.message} /><PasswordInput label="Password" {...form.register('password')} autoComplete="current-password" error={form.formState.errors.password?.message} />{mutation.isError && <Alert color="red" variant="light">Could not sign in. Check the credentials and Core status.</Alert>}<Button className="button button-primary" type="submit" loading={mutation.isPending} leftSection={<Send size={16} />}>{mutation.isPending ? 'Signing in...' : 'Enter workspace'}</Button></form></section></main>
}

function Sidebar({ view, setView, onLogout, collapsed, setCollapsed }: { view: View; setView: (view: View) => void; onLogout: () => void; collapsed: boolean; setCollapsed: (value: boolean) => void }) {
  const items: Array<{ id: View; label: string; icon: typeof LayoutDashboard }> = [{ id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard }, { id: 'content', label: 'Content', icon: FileText }, { id: 'comments', label: 'Comments', icon: MessageCircle }, { id: 'now', label: 'Now', icon: Settings2 }, { id: 'settings', label: 'Settings', icon: SlidersHorizontal }]
  return <aside className={`sidebar ${collapsed ? 'sidebar-collapsed' : ''}`}><div className="sidebar-top"><div className="brand-mark">m<span>.</span></div><button className="icon-button" type="button" aria-label="Toggle sidebar" onClick={() => setCollapsed(!collapsed)}><Menu size={18} /></button></div><nav className="side-nav">{items.map(({ id, label, icon: Icon }) => <button key={id} className={view === id ? 'side-link active' : 'side-link'} type="button" onClick={() => setView(id)}><Icon size={18} /><span>{label}</span></button>)}</nav><button className="side-link side-logout" type="button" onClick={onLogout}><LogOut size={18} /><span>Sign out</span></button></aside>
}

function Dashboard({ token }: { token: string }) {
  const client = useMemo(() => createAdminClient(token), [token])
  const query = useQuery({ queryKey: ['admin-stats'], queryFn: () => client.adminStats() })
  const stats = query.data?.content
  const chartData = stats ? [{ name: 'Posts', value: stats.postCount }, { name: 'Notes', value: stats.noteCount }, { name: 'Research', value: stats.researchCount }] : []
  return <section className="workspace"><div className="page-heading"><div><p className="kicker">Overview</p><h1>Good morning, operator.</h1><p className="subheading">A quiet view of what is moving through the garden.</p></div><button className="button button-ghost" type="button" onClick={() => query.refetch()}><RefreshCw size={16} /> Refresh</button></div>{query.isError && <p className="callout error">The dashboard could not reach Core.</p>}<div className="metric-grid"><Metric label="Published pieces" value={stats?.contentCount ?? '—'} icon={<FileText size={18} />} /><Metric label="Words in garden" value={stats?.wordCount ?? '—'} icon={<BarChart3 size={18} />} /><Metric label="Research notes" value={stats?.researchCount ?? '—'} icon={<Settings2 size={18} />} /><Metric label="Pending comments" value={query.data?.pendingComments ?? '—'} icon={<MessageCircle size={18} />} /></div><div className="dashboard-grid"><section className="panel chart-panel"><div className="panel-heading"><div><p className="kicker">Composition</p><h2>Published by kind</h2></div></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#deded5" /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#6d766f', fontSize: 12 }} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{ fill: '#6d766f', fontSize: 12 }} /><Tooltip cursor={{ fill: '#f3eee6' }} /><Bar dataKey="value" fill="#b54d37" radius={[2, 2, 0, 0]} /></BarChart></ResponsiveContainer></div></section><section className="panel quick-panel"><div className="panel-heading"><div><p className="kicker">Operator queue</p><h2>Next actions</h2></div></div><ul className="action-list"><li><MessageCircle size={17} /><span><strong>{query.data?.pendingComments ?? 0}</strong> comments waiting for review</span></li><li><FileText size={17} /><span><strong>{stats?.contentCount ?? 0}</strong> published pieces visible to readers</span></li><li><Settings2 size={17} /><span>Current status is editable from the Now view</span></li></ul></section></div></section>
}

function Metric({ label, value, icon }: { label: string; value: string | number; icon: React.ReactNode }) { return <article className="metric-card"><span className="metric-icon">{icon}</span><strong>{value}</strong><span>{label}</span></article> }

function ContentWorkspace({ token }: { token: string }) {
  const client = useMemo(() => createAdminClient(token), [token])
  const queryClient = useQueryClient()
  const [selected, setSelected] = useState<Content | null>(null)
  const [kindFilter, setKindFilter] = useState<'ALL' | Content['kind']>('ALL')
  const [statusFilter, setStatusFilter] = useState<'ALL' | Content['status']>('ALL')
  const contents = useQuery({ queryKey: ['admin-content', kindFilter, statusFilter], queryFn: () => client.adminContent({ kind: kindFilter === 'ALL' ? undefined : kindFilter, status: statusFilter === 'ALL' ? undefined : statusFilter }) })
  const filteredContents = contents.data?.data ?? []
  const form = useForm<ContentForm>({ resolver: zodResolver(contentSchema), defaultValues: { kind: 'POST', slug: '', title: '', summary: '', body: '', tags: '' } })
  const resetForm = (content?: Content) => { setSelected(content ?? null); form.reset(content ? { kind: content.kind, slug: content.slug, title: content.title, summary: content.summary, body: content.body ?? '', tags: content.tags.join(', ') } : { kind: 'POST', slug: '', title: '', summary: '', body: '', tags: '' }) }
  const save = useMutation({ mutationFn: (input: ContentForm) => selected ? client.updateContent(selected.id, { title: input.title, summary: input.summary, body: input.body, tags: input.tags.split(',').map((tag) => tag.trim()).filter(Boolean), expectedVersion: selected.version }) : client.createContent({ kind: input.kind, slug: input.slug, title: input.title, summary: input.summary, body: input.body, tags: input.tags.split(',').map((tag) => tag.trim()).filter(Boolean) }), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['admin-content'] }); resetForm() } })
  const transition = useMutation<Content | void, Error, { id: string; action: 'publish' | 'unpublish' | 'delete' }>({ mutationFn: ({ id, action }) => action === 'publish' ? client.publishContent(id) : action === 'unpublish' ? client.unpublishContent(id) : client.deleteContent(id), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ['admin-content'] }) })
  return <section className="workspace">
    <div className="page-heading"><div><p className="kicker">Publishing</p><h1>Content workspace.</h1><p className="subheading">Draft deliberately. Publish when the piece can stand on its own.</p></div><Button className="button button-primary" type="button" onClick={() => resetForm()} leftSection={<Plus size={16} />}>New draft</Button></div>
    <div className="content-layout">
      <section className="panel content-list"><div className="panel-heading"><div><h2>All content</h2><span className="count-badge">{filteredContents.length}</span></div><div className="filter-row"><Select id="kind-filter" aria-label="Filter by kind" value={kindFilter} onChange={(value) => setKindFilter((value ?? 'ALL') as typeof kindFilter)} data={[{ value: 'ALL', label: 'All kinds' }, { value: 'POST', label: 'Posts' }, { value: 'NOTE', label: 'Notes' }, { value: 'RESEARCH', label: 'Research' }]} /><Select id="status-filter" aria-label="Filter by status" value={statusFilter} onChange={(value) => setStatusFilter((value ?? 'ALL') as typeof statusFilter)} data={[{ value: 'ALL', label: 'All states' }, { value: 'DRAFT', label: 'Drafts' }, { value: 'PUBLISHED', label: 'Published' }, { value: 'DELETED', label: 'Deleted' }]} /></div></div>{contents.isLoading && <p className="muted">Loading content...</p>}{filteredContents.map((content) => <article className={`content-row ${selected?.id === content.id ? 'selected' : ''}`} key={content.id} onClick={() => content.status === 'DELETED' ? undefined : resetForm(content)}><div><div className="row-title"><span className={`status-dot ${content.status.toLowerCase()}`} />{content.title}</div><p>{content.kind} · {content.slug}</p></div><div className="row-actions"><span className="status-label">{content.status}</span>{content.status === 'DRAFT' && <ActionIcon color="teal" variant="light" type="button" title="Publish" aria-label={`Publish ${content.title}`} onClick={(event) => { event.stopPropagation(); transition.mutate({ id: content.id, action: 'publish' }) }}><Send size={14} /></ActionIcon>}{content.status === 'PUBLISHED' && <ActionIcon variant="light" type="button" title="Unpublish" aria-label={`Unpublish ${content.title}`} onClick={(event) => { event.stopPropagation(); transition.mutate({ id: content.id, action: 'unpublish' }) }}><X size={14} /></ActionIcon>}{content.status !== 'DELETED' && <ActionIcon color="red" variant="light" type="button" title="Delete" aria-label={`Delete ${content.title}`} onClick={(event) => { event.stopPropagation(); transition.mutate({ id: content.id, action: 'delete' }) }}><Trash2 size={14} /></ActionIcon>}</div></article>)}</section>
      <section className="panel editor-panel"><div className="panel-heading"><div><p className="kicker">{selected ? 'Edit entry' : 'New entry'}</p><h2>{selected ? selected.title : 'Start a draft'}</h2></div>{selected && <ActionIcon variant="subtle" type="button" aria-label="Clear editor" onClick={() => resetForm()}><X size={18} /></ActionIcon>}</div><form className="form-stack" onSubmit={form.handleSubmit((input) => save.mutate(input))}><div className="form-grid"><Select label="Kind" value={form.watch('kind')} onChange={(value) => form.setValue('kind', (value ?? 'POST') as ContentForm['kind'])} disabled={Boolean(selected)} data={[{ value: 'POST', label: 'Post' }, { value: 'NOTE', label: 'Note' }, { value: 'RESEARCH', label: 'Research' }]} /><TextInput label="Slug" {...form.register('slug')} placeholder="a-stable-slug" disabled={Boolean(selected)} error={form.formState.errors.slug?.message} /></div><TextInput label="Title" {...form.register('title')} placeholder="A title that earns its space" error={form.formState.errors.title?.message} /><Textarea label="Summary" {...form.register('summary')} minRows={2} placeholder="A compact description for the stream" /><Textarea label="Body" {...form.register('body')} minRows={12} placeholder="Markdown is welcome" error={form.formState.errors.body?.message} /><TextInput label="Tags" {...form.register('tags')} placeholder="systems, design" />{save.isError && <Alert color="red" variant="light">Could not save this entry. Check the fields and try again.</Alert>}<Button className="button button-primary" type="submit" loading={save.isPending} leftSection={<Save size={16} />}>{save.isPending ? 'Saving...' : selected ? 'Save changes' : 'Create draft'}</Button></form></section>
    </div>
  </section>
}

function CommentsWorkspace({ token }: { token: string }) {
  const client = useMemo(() => createAdminClient(token), [token]); const queryClient = useQueryClient(); const comments = useQuery({ queryKey: ['admin-comments'], queryFn: () => client.adminComments('PENDING') });
  const mutation = useMutation({ mutationFn: ({ id, action }: { id: string; action: 'approve' | 'reject' }) => action === 'approve' ? client.approveComment(id) : client.rejectComment(id), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['admin-comments'] }); void queryClient.invalidateQueries({ queryKey: ['admin-stats'] }) } });
  return <section className="workspace"><div className="page-heading"><div><p className="kicker">Moderation</p><h1>Keep the conversation kind.</h1><p className="subheading">Review public responses before they become part of the garden.</p></div><Badge className="queue-badge" leftSection={<MessageCircle size={15} />}>{comments.isLoading ? 'Loading' : `${comments.data?.data.length ?? 0} pending`}</Badge></div><section className="panel moderation-panel">{comments.isLoading && <p className="muted">Loading queue...</p>}{comments.data?.data.length === 0 && <div className="empty-state"><Check size={28} /><h2>Queue is clear.</h2><p>There is nothing waiting for review.</p></div>}<div className="moderation-list">{comments.data?.data.map((comment: Comment) => { const authorName = comment.authorName || 'Anonymous'; return <article className="moderation-row" key={comment.id}><div className="comment-avatar">{authorName.slice(0, 1).toUpperCase()}</div><div className="moderation-body"><div className="row-title">{authorName}<span>{new Date(comment.createdAt).toLocaleDateString()}</span></div><p>{comment.body}</p><small>Content ID: {comment.contentId}</small></div><div className="row-actions"><ActionIcon color="teal" variant="light" type="button" title="Approve" aria-label={`Approve comment from ${authorName}`} onClick={() => mutation.mutate({ id: comment.id, action: 'approve' })} disabled={mutation.isPending}><Check size={15} /></ActionIcon><ActionIcon color="red" variant="light" type="button" title="Reject" aria-label={`Reject comment from ${authorName}`} onClick={() => mutation.mutate({ id: comment.id, action: 'reject' })} disabled={mutation.isPending}><X size={15} /></ActionIcon></div></article> })}</div></section></section>
}

function NowWorkspace({ token }: { token: string }) {
  const client = useMemo(() => createAdminClient(token), [token]); const queryClient = useQueryClient(); const current = useQuery({ queryKey: ['now'], queryFn: () => client.now() }); const form = useForm<NowForm>({ resolver: zodResolver(nowSchema), values: current.data ? { title: current.data.title, detail: current.data.detail, mood: current.data.mood } : undefined });
  const mutation = useMutation({ mutationFn: (input: NowForm) => client.updateNow({ ...input, updatedAt: current.data?.updatedAt ?? new Date().toISOString() } as NowStatus), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ['now'] }) });
  return <section className="workspace"><div className="page-heading"><div><p className="kicker">Presence</p><h1>What is alive now?</h1><p className="subheading">A small signal for what has your attention today.</p></div></div><section className="panel narrow-panel"><div className="panel-heading"><div><p className="kicker">Public beacon</p><h2>Now status</h2></div><Badge color="teal" variant="light" leftSection={<span className="status-dot published" />}>Live</Badge></div><form className="form-stack" onSubmit={form.handleSubmit((input) => mutation.mutate(input))}><TextInput label="Title" {...form.register('title')} placeholder="Building something small" error={form.formState.errors.title?.message} /><Textarea label="Detail" {...form.register('detail')} minRows={6} placeholder="What is taking shape?" /><TextInput label="Mood" {...form.register('mood')} placeholder="FOCUSED" error={form.formState.errors.mood?.message} /><Button className="button button-primary" type="submit" loading={mutation.isPending} leftSection={<Save size={16} />}>{mutation.isPending ? 'Updating...' : 'Update now'}</Button>{mutation.isSuccess && <p className="success-text">Now status updated.</p>}</form></section></section>
}

function App() {
  const [session, setSession] = useState<Session | null>(() => { const value = readStoredSession(); return value && value.expiresAt > Date.now() ? value : null }); const [view, setView] = useState<View>('dashboard'); const [collapsed, setCollapsed] = useState(false);
  if (!session) return <LoginScreen onLogin={setSession} />
  const logout = () => { clearSession(); setSession(null) }
  return <div className="admin-shell"><Sidebar view={view} setView={setView} onLogout={logout} collapsed={collapsed} setCollapsed={setCollapsed} /><main className="admin-main"><header className="topbar"><span className="mobile-brand">manifold.</span><span className="operator"><span className="operator-dot" /> {session.username}</span></header>{view === 'dashboard' && <Dashboard token={session.accessToken} />}{view === 'content' && <ContentWorkspace token={session.accessToken} />}{view === 'comments' && <CommentsWorkspace token={session.accessToken} />}{view === 'now' && <NowWorkspace token={session.accessToken} />}{view === 'settings' && <SettingsWorkspace token={session.accessToken} />}</main></div>
}

export default App
