import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ActionIcon, Alert, Button, Select, Textarea, TextInput } from '@mantine/core'
import { Plus, Save, Send, Trash2, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useForm } from 'react-hook-form'
import type { Content } from '@manifold/contracts'
import { z } from 'zod'
import { createAdminClient } from '../api'

const contentSchema = z.object({ kind: z.enum(['POST', 'NOTE', 'RESEARCH']), slug: z.string().trim().min(1, 'Slug is required.'), title: z.string().trim().min(1, 'Title is required.'), summary: z.string().max(4000), body: z.string().min(1, 'Body is required.'), tags: z.string() })
type ContentForm = z.infer<typeof contentSchema>

export function ContentWorkspace({ token }: { token: string }) {
  const client = useMemo(() => createAdminClient(token), [token])
  const queryClient = useQueryClient()
  const [selected, setSelected] = useState<Content | null>(null)
  const [kindFilter, setKindFilter] = useState<'ALL' | Content['kind']>('ALL')
  const [statusFilter, setStatusFilter] = useState<'ALL' | Content['status']>('ALL')
  const contents = useQuery({ queryKey: ['admin-content', kindFilter, statusFilter], queryFn: () => client.adminContent({ kind: kindFilter === 'ALL' ? undefined : kindFilter, status: statusFilter === 'ALL' ? undefined : statusFilter }) })
  const filteredContents = contents.data?.data ?? []
  const form = useForm<ContentForm>({ resolver: zodResolver(contentSchema), defaultValues: { kind: 'POST', slug: '', title: '', summary: '', body: '', tags: '' } })
  const resetForm = (content?: Content) => { setSelected(content ?? null); form.reset(content ? { kind: content.kind, slug: content.slug, title: content.title, summary: content.summary, body: content.body ?? '', tags: content.tags.join(', ') } : { kind: 'POST', slug: '', title: '', summary: '', body: '', tags: '' }) }
  const save = useMutation({ mutationFn: (input: ContentForm) => selected ? client.updateContent(selected.id, { title: input.title, summary: input.summary, body: input.body, tags: input.tags.split(',').map((tag) => tag.trim()).filter(Boolean), expectedVersion: selected.version }) : client.createContent({ kind: input.kind, slug: input.slug, title: input.title, summary: input.summary, body: input.body, tags: input.tags.split(',').map((tag) => tag.trim()).filter(Boolean) }), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['admin-content'] }); resetForm() } })
  const transition = useMutation<Content | void, Error, { id: string; action: 'publish' | 'unpublish' | 'delete' }>({ mutationFn: ({ id, action }) => action === 'publish' ? client.publishContent(id) : action === 'unpublish' ? client.unpublishContent(id) : client.deleteContent(id), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ['admin-content'] }) })
  return <section className="workspace">
    <div className="page-heading"><div><p className="kicker">Publishing</p><h1>Content workspace.</h1><p className="subheading">Draft deliberately. Publish when the piece can stand on its own.</p></div><Button className="button button-primary" type="button" onClick={() => resetForm()} leftSection={<Plus size={16} />}>New draft</Button></div>
    <div className="content-layout">
      <section className="panel content-list"><div className="panel-heading"><div><h2>All content</h2><span className="count-badge">{filteredContents.length}</span></div><div className="filter-row"><Select id="kind-filter" aria-label="Filter by kind" value={kindFilter} onChange={(value) => setKindFilter((value ?? 'ALL') as typeof kindFilter)} data={[{ value: 'ALL', label: 'All kinds' }, { value: 'POST', label: 'Posts' }, { value: 'NOTE', label: 'Notes' }, { value: 'RESEARCH', label: 'Research' }]} /><Select id="status-filter" aria-label="Filter by status" value={statusFilter} onChange={(value) => setStatusFilter((value ?? 'ALL') as typeof statusFilter)} data={[{ value: 'ALL', label: 'All states' }, { value: 'DRAFT', label: 'Drafts' }, { value: 'PUBLISHED', label: 'Published' }, { value: 'DELETED', label: 'Deleted' }]} /></div></div>{contents.isLoading && <p className="muted">Loading content...</p>}{filteredContents.map((content) => <article className={`content-row ${selected?.id === content.id ? 'selected' : ''}`} key={content.id} onClick={() => content.status === 'DELETED' ? undefined : resetForm(content)}><div><div className="row-title"><span className={`status-dot ${content.status.toLowerCase()}`} />{content.title}</div><p>{content.kind} · {content.slug}</p></div><div className="row-actions"><span className="status-label">{content.status}</span>{content.status === 'DRAFT' && <ActionIcon color="teal" variant="light" type="button" title="Publish" aria-label={`Publish ${content.title}`} onClick={(event) => { event.stopPropagation(); transition.mutate({ id: content.id, action: 'publish' }) }}><Send size={14} /></ActionIcon>}{content.status === 'PUBLISHED' && <ActionIcon variant="light" type="button" title="Unpublish" aria-label={`Unpublish ${content.title}`} onClick={(event) => { event.stopPropagation(); transition.mutate({ id: content.id, action: 'unpublish' }) }}><X size={14} /></ActionIcon>}{content.status !== 'DELETED' && <ActionIcon color="red" variant="light" type="button" title="Delete" aria-label={`Delete ${content.title}`} onClick={(event) => { event.stopPropagation(); transition.mutate({ id: content.id, action: 'delete' }) }}><Trash2 size={14} /></ActionIcon>}</div></article>)}</section>
      <section className="panel editor-panel"><div className="panel-heading"><div><p className="kicker">{selected ? 'Edit entry' : 'New entry'}</p><h2>{selected ? selected.title : 'Start a draft'}</h2></div>{selected && <ActionIcon variant="subtle" type="button" aria-label="Clear editor" onClick={() => resetForm()}><X size={18} /></ActionIcon>}</div><form className="form-stack" onSubmit={form.handleSubmit((input) => save.mutate(input))}><div className="form-grid"><Select label="Kind" value={form.watch('kind')} onChange={(value) => form.setValue('kind', (value ?? 'POST') as ContentForm['kind'])} disabled={Boolean(selected)} data={[{ value: 'POST', label: 'Post' }, { value: 'NOTE', label: 'Note' }, { value: 'RESEARCH', label: 'Research' }]} /><TextInput label="Slug" {...form.register('slug')} placeholder="a-stable-slug" disabled={Boolean(selected)} error={form.formState.errors.slug?.message} /></div><TextInput label="Title" {...form.register('title')} placeholder="A title that earns its space" error={form.formState.errors.title?.message} /><Textarea label="Summary" {...form.register('summary')} minRows={2} placeholder="A compact description for the stream" /><Textarea label="Body" {...form.register('body')} minRows={12} placeholder="Markdown is welcome" error={form.formState.errors.body?.message} /><TextInput label="Tags" {...form.register('tags')} placeholder="systems, design" />{save.isError && <Alert color="red" variant="light">Could not save this entry. Check the fields and try again.</Alert>}<Button className="button button-primary" type="submit" loading={save.isPending} leftSection={<Save size={16} />}>{save.isPending ? 'Saving...' : selected ? 'Save changes' : 'Create draft'}</Button></form></section>
    </div>
  </section>
}

export default ContentWorkspace
