const en = {
  language: { label: 'Language', english: 'English', chinese: '简体中文' },
  common: {
    anonymous: 'Anonymous', cancel: 'Cancel', delete: 'Delete', discard: 'Discard', edit: 'Edit', hidden: 'hidden', deleted: 'deleted', loading: 'Loading…', remove: 'Remove', reload: 'Reload', restore: 'Restore', save: 'Save', saved: 'Saved', upload: 'Upload', uploaded: 'Uploaded', preview: 'Preview', details: 'Details', copied: 'Copied', copyMarkdown: 'Copy markdown', openPreview: 'Open preview', moveUp: 'Move up', moveDown: 'Move down', previousPage: 'Previous page', nextPage: 'Next page', pageOf: 'Page {{page}} of {{total}}', unsavedChanges: 'Unsaved changes', keepEditing: 'Keep editing', togglePasswordVisibility: 'Toggle password visibility', closeDialog: 'Close dialog', writings: 'Writings', writing: 'Writing', thoughts: 'Thoughts', thought: 'Thought', comments: 'Comments', media: 'Media', profile: 'Profile', settings: 'Settings', dashboard: 'Dashboard', status: { draft: 'Draft', published: 'Published', deleted: 'Deleted' }, count: { comments_one: '{{count}} comment', comments_other: '{{count}} comments', files_one: '{{count}} file', files_other: '{{count}} files', links_one: '{{count}} link', links_other: '{{count}} links', cards_one: '{{count}} card', cards_other: '{{count}} cards', references_one: '{{count}} reference', references_other: '{{count}} references', active_one: '{{count}} active', active_other: '{{count}} active', events_one: '{{count}} event', events_other: '{{count}} events', entries_one: '{{count}} entry', entries_other: '{{count}} entries' }
  },
  validation: {
    requiredUsername: 'Username is required.', passwordMin: 'Password must be at least 8 characters.', currentPasswordRequired: 'Current password is required.', newPasswordMin: 'New password must be at least 8 characters.', passwordsMismatch: 'Passwords do not match.', requiredTitle: 'Title is required.', titleMax: 'Keep the title under 80 characters.', descriptionMax: 'Keep the description under 200 characters.', footerMax: 'Keep the footer text under 200 characters.', requiredLabel: 'Label is required.', labelMax: 'Keep labels under 80 characters.', requiredUrl: 'URL is required.', urlMax: 'Keep URLs under 200 characters.', socialMax: 'At most 6 social links.', navigationMin: 'Add at least one navigation link.', navigationMax: 'At most 10 navigation links.', sectionsMin: 'Keep at least one homepage section.', httpUrl: 'Use an http(s) URL', contactUrl: 'Use an http(s) or mailto URL', periodRequired: 'Period is required', institutionRequired: 'Institution is required', programRequired: 'Program is required', organizationRequired: 'Organization is required', roleRequired: 'Role is required', nameRequired: 'Name is required', valueRequired: 'This field is required.', maxCharacters: 'Must be at most {{count}} characters.', slugRequired: 'Slug is required.', contentRequired: 'Content is required.'
  },
  login: { kicker: 'Private workspace', title: 'Manage the site.', copy: 'Publish content, review comments, and update the profile.', username: 'Username', password: 'Password', error: 'Could not sign in. Check the credentials and Core status.', signingIn: 'Signing in…', submit: 'Enter workspace' },
  nav: { toggle: 'Toggle sidebar', signOut: 'Sign out', loadingWorkspace: 'Loading workspace…' },
  app: { unsavedTitle: 'Unsaved changes', unsavedLeave: 'Discard unsaved changes and leave this page?', discardLeave: 'Discard and leave' },
  errorBoundary: { kicker: 'Workspace interruption', title: 'The workspace needs another pass.', copy: 'The management view stopped unexpectedly. Core data remains unchanged.', reload: 'Reload workspace', reference: 'Reference: {{id}}' },
  pager: { pageOf: 'Page {{page}} of {{total}}' },
  chips: { placeholder: 'Add and press Enter', remove: 'Remove {{value}}' },
  saveBar: { unsaved: 'Unsaved changes', discard: 'Discard', saved: 'Saved' },
  confirm: { cancel: 'Cancel' },
  links: { label: 'Label', destination: 'Label or /path, or full URL', external: 'Opens in a new tab' },
  editor: {
    back: 'Back to {{kind}}s', publish: 'Publish', publishNow: 'Publish now', publishConfirm: 'Publish this {{kind}} to the public site?', unpublish: 'Unpublish', unpublishConfirm: 'Take this {{kind}} off the public site? It returns to drafts.', viewSite: 'View on the site', deleteLabel: 'Delete {{kind}}', deleteConfirm: 'Delete this {{kind}}? It leaves the public site immediately.', newKicker: '{{kind}} · New', newTitle: 'A new {{kind}}', updated: 'Updated {{date}} · v{{version}}', updatedDirty: 'Updated {{date}} · v{{version}} · unsaved changes', lock: 'Lock', edit: 'Edit', tabs: { meta: 'Meta', context: 'Context', render: 'Render', comments: 'Comments' }, saveChanges: 'Save changes', saveDraft: 'Save draft', lockConfirm: 'Discard unsaved changes and lock this {{kind}}?', discardLock: 'Discard and lock', savedElsewhere: 'Saved elsewhere', conflict: 'This {{kind}} changed in another session. Reload it to continue editing.'
  },
  list: {
    search: 'Search {{kind}}s', statusFilter: 'Status filter', all: 'All', drafts: 'Drafts', published: 'Published', deleted: 'Deleted', pinned: 'Pinned', sort: 'Sort', newest: 'Newest', oldest: 'Oldest', updated: 'Recently updated', loadError: 'The list could not be loaded. Please try again.', empty: 'No {{kind}}s match the current filters.', untitled: 'Untitled {{kind}}', open: 'Open {{title}}', unpinTitle: 'Unpin from the archive', pinTitle: 'Pin to the archive', unpin: 'Unpin {{title}}', pin: 'Pin {{title}}', viewNamed: 'View {{title}} on the site', publishNamed: 'Publish {{title}}', unpublishNamed: 'Unpublish {{title}}', deleteNamed: 'Delete {{title}}', restoreNamed: 'Restore {{title}}', unpublishConfirm: 'Take this piece off the public site? It returns to drafts.', deleteConfirm: 'Delete this piece? It leaves the public site immediately.', restoreConfirm: 'Restore this {{kind}} to drafts?'
  },
  comments: {
    search: 'Search comments', loadError: 'Comments could not be loaded. Please try again.', noMatch: 'No comments match this search.', none: 'No comments yet.', noneThread: 'No comments yet — start the thread below.', postError: 'The comment could not be posted. Try again.', updateError: 'The comment could not be updated. Try again.', authorUpdateError: 'The author details could not be updated. Try again.', replying: 'Replying to {{author}} · {{body}}', author: 'Author', authorDescription: 'Prefilled from your profile; left empty the comment posts as Anonymous.', reply: 'Reply', comment: 'Comment', answer: 'Answer {{author}}…', write: 'Write a note in this thread…', postReply: 'Post reply', postComment: 'Post comment', editAuthor: 'Edit author', name: 'Name', website: 'Website', avatarSeed: 'Avatar seed', saveAuthor: 'Save author', restoreBody: 'Make this comment visible on the public site again.', unhide: 'Unhide', hide: 'Hide', hideBody: 'Hide this comment from the public site? Its replies remain visible.', deleteBody: 'Delete this comment? It leaves the public site immediately.', moderationKicker: 'Moderation', moderationTitle: 'Manage comments.', moderationCopy: 'Comments are public immediately. Soft-delete anything that does not belong.', total: '{{count}} total', readerEmpty: 'Reader responses will appear here.', replyTag: 'reply', openThread: 'Open the {{kind}} thread for a comment by {{author}}', restoreFrom: 'Restore comment from {{author}}', unhideFrom: 'Unhide comment from {{author}}', hideFrom: 'Hide comment from {{author}}', deleteFrom: 'Delete comment from {{author}}', softDeleteBody: 'Soft-delete this comment? It leaves the public site immediately.', deletedAt: 'deleted {{date}}'
  },
  security: {
    kicker: 'Security', title: 'Credentials and sessions', change: 'Change password', changeError: 'Password could not be updated. Check the current password and try again.', currentPassword: 'Current password', newPassword: 'New password', confirmPassword: 'Confirm new password', minPlaceholder: 'At least 8 characters', updated: 'Password updated', sessions: 'Active sessions', sessionsError: 'Sessions could not be loaded.', revokeError: 'That session could not be signed out.', thisDevice: 'This device', signedIn: 'signed in {{date}}', current: 'Current', active: 'Active', revoked: 'Revoked', expires: 'expires {{date}}', signOutSession: 'Sign out session {{id}}', signOut: 'Sign out', signOutConfirm: 'Sign out this session? Its token stops working immediately.', none: 'No active sessions found.', revokedAll: 'Sessions revoked', signOutEverywhere: 'Sign out everywhere'
  },
  dashboard: {
    kicker: 'Overview', title: 'Dashboard', copy: 'Content, traffic, activity, and system health at a glance.', refresh: 'Refresh', error: 'The dashboard could not reach Core.', metrics: { published: 'Published', drafts: 'Drafts', views: 'Total views', likes: 'Likes', comments: 'Comments', visitors: 'Visitors now' }, growth: 'Content growth', growthHint: 'Created vs published per month', created: 'Created', published: 'Published', viewsDays: 'Views · last {{days}} days', uniqueVisitors: '{{count}} unique visitors', uniqueVisitorsLabel: 'Unique visitors', views: 'Views', ranking: 'Ranking', topContent: 'Top content', topFive: 'Top 5', topEmpty: 'Published content will rank here as views come in.', topMeta: '{{kind}} · {{views}} views · {{likes}} likes · {{comments}} comments', tagDistribution: 'Tag distribution', tagHint: 'Top 10 by published usage', content: 'Content', community: 'Community', recentComments: 'Recent comments', noMatchingComments: 'No matching comments.', noComments: 'No comments yet.', audit: 'Audit', recentActivity: 'Recent activity', searchActivity: 'Search activity', noMatchingActivity: 'No matching activity.', activityEmpty: 'Activity will appear here as the garden changes.', trend: 'Trend', system: 'System', coreHealth: 'Core health', healthy: 'Healthy', unavailable: 'System metrics unavailable.', refreshSystem: 'Refresh system status', cpu: 'CPU', memory: 'Memory', disk: 'Disk', version: 'Version', uptime: 'Uptime', host: 'Host', loadAverage: 'Load average', processRss: 'Process RSS', heap: 'Heap', goroutines: 'Goroutines', database: 'Database', contentCache: 'Content cache', auditEvents: 'Audit events', startedAt: 'Started at', cores: '{{count}} cores', used: 'Used', free: 'Free', uptimeDays: '{{days}}d {{hours}}h', uptimeHours: '{{hours}}h {{minutes}}m', uptimeMinutes: '{{minutes}}m', relativeNow: 'just now', relativeMinutes: '{{count}}m ago', relativeHours: '{{count}}h ago', relativeDays: '{{count}}d ago', events: { signedIn: 'Signed in', contentCreated: 'Content created', contentUpdated: 'Content updated', contentPublished: 'Content published', contentUnpublished: 'Content unpublished', contentDeleted: 'Content deleted', contentViewed: 'Content viewed', likeAdded: 'Like added', likeRemoved: 'Like removed', commentPosted: 'Comment posted', commentRemoved: 'Comment removed', commentRestored: 'Comment restored', profileUpdated: 'Profile updated', siteUpdated: 'Site composition updated', thoughtsUpdated: 'Thoughts config updated' }
  },
  profile: {
    pageKicker: 'Identity', pageTitle: 'Profile.', pageCopy: 'The identity, background, and links shown on the public homepage.', loadError: 'Profile could not be loaded.', saveError: 'Profile could not be saved. Fix the highlighted fields and try again.', sectionsAria: 'Profile sections', identity: 'Identity', links: 'Links', interests: 'Interests', cv: 'CV', series: 'Series', contact: 'Contact', introduction: 'Introduction', websiteResume: 'Website and resume', background: 'Background', mySeries: 'My Series', displayName: 'Display name', handle: 'Handle', location: 'Location', headline: 'Headline', bio: 'Bio', organization: 'Organization', organizationDescription: 'Shown above the bio on the homepage.', avatarUrl: 'Avatar URL', previewAvatar: 'Preview avatar', avatarPreview: 'Avatar preview', imageTypes: 'Only PNG, JPEG, WebP, GIF and AVIF images are accepted.', avatarUploadError: 'Avatar upload failed.', websiteUrl: 'Website URL', resumeUrl: 'Resume PDF URL', resumeDescription: 'CV badge next to the portrait.', previewResume: 'Preview resume', pdfOnly: 'Only PDF files are accepted.', resumeUploadError: 'Resume upload failed.', tags: 'Tags', addInterest: 'Add interest and press Enter', tagsHint: 'Rendered as #tags under the introduction.', educationExperience: 'Education and experience', backgroundSection: 'Background section', education: 'Education', experience: 'Experience', contactLinks: 'Contact links', addLink: 'Add link', addSeries: 'Add series', addEducation: 'Add education', addExperience: 'Add experience', chooseIcon: 'Choose icon', label: 'Label', url: 'URL', category: 'Category', description: 'Description', name: 'Name', institution: 'Institution', program: 'Program', role: 'Role', period: 'Period', editPeriod: 'Edit period', edit: 'Edit', legacyPeriod: 'Stored as free text — use the pickers to replace it.', from: 'From', to: 'To', startMonth: 'Start month', endMonth: 'End month', now: 'Now', openEnded: 'Open-ended — pick an end month to close it.', leaveEmpty: 'Leave To empty to mark it as “Now”.', clearPeriod: 'Clear period', iconFallback: 'Falls back to the globe icon — pick an icon or adjust the label.', iconRenders: 'Renders as {{icon}} on the homepage.', preview: 'Preview', yourName: 'Your name', noWebsite: 'No website URL yet.', website: 'Website', resume: 'Resume', pdfDownload: 'PDF download', noResume: 'No resume PDF yet.', noInterests: 'No interests yet.', noBackground: 'No education or experience yet.', noSeries: 'No series yet.', noPublicLinks: 'No public links yet.', locationPreview: 'Location shows as “{{location}} · UTC+8”.', saveProfile: 'Save profile'
  },
  settings: {
    kicker: 'Configuration', title: 'Site settings.', copy: 'Identity, navigation, comments, and homepage composition for the public site.', loadError: 'Site configuration could not be loaded.', saveError: 'Site configuration could not be saved. Fix the highlighted fields and try again.', identity: 'Identity', identityTitle: 'Title, description, and footer', siteTitle: 'Site title', siteTitleDescription: 'Drives the browser title, SEO metadata, and RSS channel name.', description: 'Description', descriptionHelp: '{{count}}/200 · Used as the default SEO and RSS description.', footer: 'Footer text', footerHelp: '{{count}}/200 · Shown on the bottom line of every page.', socialLinks: 'Social links', addSocial: 'Add social link', navigation: 'Navigation', primaryNavigation: 'Primary navigation', addNavigation: 'Add navigation link', navigationHint: 'Internal links look like /writing or /thoughts; external links use full URLs.', comments: 'Comments', publicDiscussions: 'Public discussions', allowComments: 'Allow public comments', commentsDescription: 'When off, comment forms disappear from the site and the public API rejects new comments with 403.', homepage: 'Homepage', sections: 'Sections', homepageSections: 'Homepage sections', save: 'Save site settings', section: { profile: 'Profile', background: 'Background', recentContent: 'Recent content', updates: 'Updates', series: 'My Series', contact: 'Contact' }, moveUp: 'Move {{section}} up', moveDown: 'Move {{section}} down'
  },
  writings: {
    kicker: 'Writings', title: 'Writings worth returning to.', copy: 'Deep technical pieces with the full reading surface.', new: 'New writing', pin: 'Pin to the writings archive', pinDescription: 'Pins this piece in the Featured row at the top of the public Writings page. Multiple pieces can be pinned.', pinError: 'The pin could not be updated.', loadError: 'This writing could not be loaded. Go back and try again.', titleLabel: 'Title', titlePlaceholder: 'A title with a clear promise', slug: 'Slug', slugPlaceholder: 'a-readable-url', summary: 'Summary', summaryDescription: '✦ {{count}}/4000 — shown on archive cards', tags: 'Tags', addTag: 'Add tag and press Enter', language: 'Language', languageDescription: 'The language the piece is written in, shown in the article meta line', languagePlaceholder: 'e.g. English', languagePresetOther: 'Other', readingTime: 'Estimated reading time', minutes: '{{count}} min', recalculated: 'Core recalculates this on save', aiAssisted: 'AI-assisted writing', aiDescription: 'Lets readers filter this piece out with “No AI writing”', saveError: 'Could not save this writing. Check the fields and Core status.', editorHint: 'Write in the instant-rendering editor — headings, lists, code and math format as you type; images paste, drop or upload from the toolbar and are stored in Core. The stored value is plain Markdown.', minRead: '{{count}} min read'
  },
  thoughts: {
    kicker: 'Thoughts', title: 'Capture as you go.', copy: 'Fragments, methods, and reading notes that stay light.', new: 'New thought', pin: 'Pin to the thoughts archive', pinDescription: 'Pins this thought in the Featured row at the top of the public Thoughts page. Multiple thoughts can be pinned.', pinError: 'The pin could not be updated.', loadError: 'This thought could not be loaded. Go back and try again.', titleLabel: 'Title', optional: 'Optional', slug: 'Slug', slugPlaceholder: 'a-readable-url', summary: 'Summary', summaryDescription: '✦ {{count}}/4000 — shown with the ✦ mark on cards', tags: 'Tags', addTag: 'Add tag and press Enter', provenance: 'Provenance', mood: 'Mood', moodDescription: 'Sparkles — a short state of mind', question: 'Question', questionDescription: 'Rendered as the reflection blockquote', context: 'Context', contextDescription: 'Compass — where it came from', source: 'Source', sourceDescription: 'Book — book, paper, or conversation', saveError: 'Could not save this thought. Check the fields and Core status.', editorHint: 'Write in the instant-rendering editor — images paste, drop or upload from the toolbar and are stored in Core. The stored value is plain Markdown.'
  },
  media: {
    title: 'Files stored beside the words.', copy: 'Uploads live in Core — images render inline, PDFs link from the profile.', search: 'Search media', dropzoneAria: 'Upload images or PDFs', dropzone: 'Drop images or PDFs here or click to upload — paste and drag also work inside the editor.', uploading: 'Uploading…', accepted: 'Only PNG, JPEG, WebP, GIF, AVIF images and PDF files are accepted.', uploadError: 'Media upload failed.', deleteInUse: 'This file is used in published or draft content. Remove those references first.', deleteError: 'Media could not be deleted.', listError: 'The media list could not be loaded. Please try again.', open: 'Open {{filename}}', deleteNamed: 'Delete {{filename}}', deleteConfirm: 'Delete this file? Anything referencing it will show as broken.', noMatch: 'No files match the current filters.', none: 'No files uploaded yet — drop images or PDFs above or paste into the editor.', back: 'Back to media', notFound: 'This file could not be found. It may have been deleted.', uploadedAt: 'Uploaded {{date}} · {{size}}', type: 'Type', size: 'Size', uploaded: 'Uploaded', id: 'ID', usedBy: 'Used by', references: 'References', refsError: 'The reference list could not be loaded. Please try again.', noRefs: 'No published or draft content references this file.', untitled: 'Untitled {{kind}}', openEditor: 'Open editor', openReference: 'Open {{title}} in the editor', loadError: 'This file could not be loaded. Please try again.', copyError: 'The Markdown reference could not be copied.'
  },
  markdown: {
    callout: 'Callout', calloutType: '{{type}} callout', calloutTypes: { note: 'Note', tip: 'Tip', important: 'Important', warning: 'Warning', caution: 'Caution' }, footnote: 'Footnote', keyboard: 'Keyboard key', highlight: 'Highlight', diff: 'Diff block', uploadImage: 'Upload image', imageAlt: 'image', unsupportedImage: 'Unsupported image type: {{name}}', uploadFailed: 'Image upload failed.', highlightPlaceholder: 'highlighted', diffAdded: 'added line', diffRemoved: 'removed line', diffPlain: 'plain line'
  }
} as const

export default en
