const zhCN = {
  language: { label: '语言', english: 'English', chinese: '简体中文' },
  common: {
    anonymous: '匿名', cancel: '取消', delete: '删除', discard: '放弃更改', edit: '编辑', hidden: '已隐藏', deleted: '已删除', loading: '加载中…', remove: '移除', reload: '重新加载', restore: '恢复', save: '保存', saved: '已保存', upload: '上传', uploaded: '已上传', preview: '预览', details: '详情', copied: '已复制', copyMarkdown: '复制 Markdown', openPreview: '打开预览', moveUp: '上移', moveDown: '下移', previousPage: '上一页', nextPage: '下一页', pageOf: '第 {{page}} 页，共 {{total}} 页', unsavedChanges: '有未保存的更改', keepEditing: '继续编辑', togglePasswordVisibility: '显示或隐藏密码', closeDialog: '关闭对话框', writings: 'Writings', writing: 'Writing', thoughts: 'Thoughts', thought: 'Thought', comments: '评论', media: '媒体', profile: '个人资料', settings: '设置', dashboard: '仪表盘', status: { draft: '草稿', published: '已发布', deleted: '已删除' }, count: { comments_one: '{{count}} 条评论', comments_other: '{{count}} 条评论', files_one: '{{count}} 个文件', files_other: '{{count}} 个文件', links_one: '{{count}} 个链接', links_other: '{{count}} 个链接', cards_one: '{{count}} 张卡片', cards_other: '{{count}} 张卡片', references_one: '{{count}} 处引用', references_other: '{{count}} 处引用', active_one: '{{count}} 个活跃会话', active_other: '{{count}} 个活跃会话', events_one: '{{count}} 个事件', events_other: '{{count}} 个事件', entries_one: '{{count}} 个条目', entries_other: '{{count}} 个条目' }
  },
  validation: {
    requiredUsername: '请输入用户名。', passwordMin: '密码至少需要 8 个字符。', currentPasswordRequired: '请输入当前密码。', newPasswordMin: '新密码至少需要 8 个字符。', passwordsMismatch: '两次输入的密码不一致。', requiredTitle: '请输入标题。', titleMax: '标题不能超过 80 个字符。', descriptionMax: '描述不能超过 200 个字符。', footerMax: '页脚文字不能超过 200 个字符。', requiredLabel: '请输入标签。', labelMax: '标签不能超过 80 个字符。', requiredUrl: '请输入 URL。', urlMax: 'URL 不能超过 200 个字符。', socialMax: '社交链接最多 6 个。', navigationMin: '请至少添加一个导航链接。', navigationMax: '导航链接最多 10 个。', sectionsMin: '请至少保留一个首页区块。', httpUrl: '请使用 http(s) URL', contactUrl: '请使用 http(s) 或 mailto URL', periodRequired: '请输入时间段', institutionRequired: '请输入院校', programRequired: '请输入专业', organizationRequired: '请输入组织', roleRequired: '请输入职位', nameRequired: '请输入名称', valueRequired: '请填写此字段。', maxCharacters: '最多 {{count}} 个字符。', slugRequired: '请输入 Slug。', contentRequired: '请输入内容。'
  },
  login: { kicker: 'Private workspace', title: '管理站点。', copy: '发布内容、审核评论并更新个人资料。', username: '用户名', password: '密码', error: '无法登录。请检查凭据和 Core 状态。', signingIn: '正在登录…', submit: '进入工作区' },
  nav: { toggle: '展开或收起侧边栏', signOut: '退出登录', loadingWorkspace: '正在加载工作区…' },
  app: { unsavedTitle: '有未保存的更改', unsavedLeave: '要放弃未保存的更改并离开此页面吗？', discardLeave: '放弃并离开' },
  errorBoundary: { kicker: 'Workspace interruption', title: '工作区需要重新加载。', copy: '管理界面意外停止，Core 数据未发生更改。', reload: '重新加载工作区', reference: '参考编号：{{id}}' },
  pager: { pageOf: '第 {{page}} 页，共 {{total}} 页' },
  chips: { placeholder: '输入后按 Enter 添加', remove: '移除 {{value}}' },
  saveBar: { unsaved: '有未保存的更改', discard: '放弃更改', saved: '已保存' },
  confirm: { cancel: '取消' },
  links: { label: '标签', destination: '标签、/path 或完整 URL', external: '在新标签页中打开' },
  editor: {
    back: '返回 {{kind}} 列表', publish: '发布', publishNow: '立即发布', publishConfirm: '将此 {{kind}} 发布到公开站点吗？', unpublish: '取消发布', unpublishConfirm: '将此 {{kind}} 从公开站点下线吗？下线后会回到草稿。', viewSite: '在站点中查看', deleteLabel: '删除 {{kind}}', deleteConfirm: '删除此 {{kind}} 吗？它会立即从公开站点移除。', newKicker: '{{kind}} · 新建', newTitle: '新建 {{kind}}', updated: '更新于 {{date}} · v{{version}}', updatedDirty: '更新于 {{date}} · v{{version}} · 有未保存的更改', lock: '锁定', edit: '编辑', tabs: { meta: '元数据', context: '正文', render: '预览', comments: 'Comments' }, saveChanges: '保存更改', saveDraft: '保存草稿', lockConfirm: '要放弃未保存的更改并锁定此 {{kind}} 吗？', discardLock: '放弃并锁定', savedElsewhere: '已在其他位置保存', conflict: '此 {{kind}} 已在另一个会话中更改。请重新加载后继续编辑。'
  },
  list: {
    search: '搜索 {{kind}}', statusFilter: '状态筛选', all: '全部', drafts: '草稿', published: '已发布', deleted: '已删除', pinned: '已置顶', sort: '排序', newest: '最新', oldest: '最早', updated: '最近更新', loadError: '无法加载列表，请重试。', empty: '没有符合当前筛选条件的 {{kind}}。', untitled: '未命名 {{kind}}', open: '打开 {{title}}', unpinTitle: '从归档中取消置顶', pinTitle: '置顶到归档', unpin: '取消置顶 {{title}}', pin: '置顶 {{title}}', viewNamed: '在站点中查看 {{title}}', publishNamed: '发布 {{title}}', unpublishNamed: '取消发布 {{title}}', deleteNamed: '删除 {{title}}', restoreNamed: '恢复 {{title}}', unpublishConfirm: '将此内容从公开站点下线吗？下线后会回到草稿。', deleteConfirm: '删除此内容吗？它会立即从公开站点移除。', restoreConfirm: '将此 {{kind}} 恢复为草稿吗？'
  },
  comments: {
    search: '搜索评论', loadError: '无法加载评论，请重试。', noMatch: '没有匹配的评论。', none: '暂无评论。', noneThread: '暂无评论，可在下方发起讨论。', postError: '无法发布评论，请重试。', updateError: '无法更新评论，请重试。', authorUpdateError: '无法更新作者信息，请重试。', replying: '回复 {{author}} · {{body}}', author: '作者', authorDescription: '默认使用个人资料中的名称；留空时将以匿名身份发布。', reply: '回复', comment: '评论', answer: '回复 {{author}}…', write: '在此讨论中写下内容…', postReply: '发布回复', postComment: '发布评论', editAuthor: '编辑作者', name: '名称', website: '网站', avatarSeed: '头像种子', saveAuthor: '保存作者', restoreBody: '让此评论重新显示在公开站点上。', unhide: '取消隐藏', hide: '隐藏', hideBody: '从公开站点隐藏此评论吗？其回复仍会显示。', deleteBody: '删除此评论吗？它会立即从公开站点移除。', moderationKicker: 'Moderation', moderationTitle: '管理评论。', moderationCopy: '评论会立即公开。可软删除不合适的内容。', total: '共 {{count}} 条', readerEmpty: '读者回复将显示在这里。', replyTag: '回复', openThread: '打开 {{author}} 在 {{kind}} 下的评论讨论', restoreFrom: '恢复 {{author}} 的评论', unhideFrom: '取消隐藏 {{author}} 的评论', hideFrom: '隐藏 {{author}} 的评论', deleteFrom: '删除 {{author}} 的评论', softDeleteBody: '软删除此评论吗？它会立即从公开站点移除。', deletedAt: '删除于 {{date}}'
  },
  agent: {
    title: 'Agent', open: '打开 Agent', close: '关闭 Agent', description: '把一个念头放进来，一起找到下一条值得追问的线索。', clear: '清空对话', clearError: '无法清空当前对话。', compactError: '无法压缩当前对话。', loadError: '无法加载当前会话的对话。', tryAgain: '关闭后重新打开 Agent 即可重试。', runError: 'Agent 暂时无法完成请求，请稍后重试。', streamEnded: 'Agent 流在运行完成前结束。', incomplete: '这次运行未能保存回答，请重新提问。', emptyTitle: '开始一段对话', you: '你', youShort: '你', assistant: 'Agent', process: 'Agent 处理过程', trace: '运行详情', thoughtDone: '已思考', toolCount_one: '{{count}} 个工具', toolCount_other: '{{count}} 个工具', thinking: '思考中', stepInProgress: '正在整理上下文', stepComplete: '上下文已准备好', stepError: '运行中断', statusReady: '就绪', statusRunning: '处理中', statusComplete: '已完成', statusTruncated: '输出已截断', statusError: '需要关注', runningTool: '调用中', toolComplete: '已完成', toolFailed: '失败', input: '输入', output: '输出', usage: '{{count}} tokens', usageBreakdown: '输入 {{input}} · 输出 {{output}}', placeholder: '输入问题或 / 指令…', composerHint: 'Enter 发送 · 输入 / 查看指令', running: '处理中…', send: '发送', sessionLabel: '安静对话', sessionMemory: '只留在本次登录中',
  },
  agentNotice: { compactCommand: '/compact', compactRunning: '正在压缩较早的对话', compactProgress: '按配置保留最近 turns，同时更新工作状态摘要。', compactComplete: '对话上下文已压缩', compactCompleteDetail: '工作摘要已更新，压缩了 {{count}} 条消息，并保留最近 {{recentTurns}} 个对话。', compactNoop: '没有需要压缩的较早对话', compactNoopDetail: '当前对话仍在配置的原始窗口内，最近 {{recentTurns}} 个对话保持可见。', compactTryAgain: '请在 Agent Provider 可用后重试。', summaryLabel: '已压缩的历史上下文', summaryAvailable: '展开查看摘要', summaryPending: '完成后可查看详情' },
  agentCommands: { menu: 'Agent 指令', compact: '立即压缩较早的对话 turns', quit: '关闭 Agent 对话框', clear: '清空当前对话与摘要' },
  agentActions: { copy: '复制', copyMessage: '复制消息', copyError: '无法复制这条消息。', undo: '撤回', undoing: '正在撤回…', undoMessage: '撤回这一轮并修改提问', undoError: '无法撤回这一轮，请重新加载对话后再试。' },
  security: {
    kicker: 'Security', title: '凭据与会话', change: '修改密码', changeError: '无法更新密码。请检查当前密码后重试。', currentPassword: '当前密码', newPassword: '新密码', confirmPassword: '确认新密码', minPlaceholder: '至少 8 个字符', updated: '密码已更新', sessions: '活跃会话', sessionsError: '无法加载会话。', revokeError: '无法退出该会话。', thisDevice: '此设备', signedIn: '登录于 {{date}}', current: '当前', active: '活跃', revoked: '已撤销', expires: '到期于 {{date}}', signOutSession: '退出会话 {{id}}', signOut: '退出', signOutConfirm: '退出此会话吗？其令牌会立即失效。', none: '未找到活跃会话。', revokedAll: '会话已撤销', signOutEverywhere: '退出所有设备'
  },
  dashboard: {
    kicker: 'Overview', title: '仪表盘', copy: '集中查看内容、流量、活动和系统健康状态。', refresh: '刷新', error: '仪表盘无法连接 Core。', metrics: { published: '已发布', drafts: '草稿', views: '总浏览量', likes: '点赞', comments: '评论', visitors: '当前访客' }, growth: '内容增长', growthHint: '每月创建与发布数量', created: '已创建', published: '已发布', viewsDays: '最近 {{days}} 天浏览量', uniqueVisitors: '{{count}} 位独立访客', uniqueVisitorsLabel: '独立访客', views: '浏览量', ranking: 'Ranking', topContent: '热门内容', topFive: '前 5 名', topEmpty: '发布内容产生浏览后会在此排名。', topMeta: '{{kind}} · {{views}} 次浏览 · {{likes}} 个赞 · {{comments}} 条评论', tagDistribution: '标签分布', tagHint: '按已发布内容使用量排名前 10', content: '内容', community: 'Community', recentComments: '最新评论', noMatchingComments: '没有匹配的评论。', noComments: '暂无评论。', audit: 'Audit', recentActivity: '最近活动', searchActivity: '搜索活动', noMatchingActivity: '没有匹配的活动。', activityEmpty: '站点发生更改后，活动会显示在这里。', trend: 'Trend', system: 'System', coreHealth: 'Core 健康状态', healthy: '健康', unavailable: '系统指标不可用。', refreshSystem: '刷新系统状态', cpu: 'CPU', memory: '内存', disk: '磁盘', version: '版本', uptime: '运行时间', host: '主机', loadAverage: '平均负载', processRss: '进程 RSS', heap: '堆内存', goroutines: 'Goroutine', database: '数据库', contentCache: '内容缓存', auditEvents: '审计事件', startedAt: '启动时间', cores: '{{count}} 核', used: '已用', free: '可用', uptimeDays: '{{days}} 天 {{hours}} 小时', uptimeHours: '{{hours}} 小时 {{minutes}} 分钟', uptimeMinutes: '{{minutes}} 分钟', relativeNow: '刚刚', relativeMinutes: '{{count}} 分钟前', relativeHours: '{{count}} 小时前', relativeDays: '{{count}} 天前', events: { signedIn: '已登录', contentCreated: '已创建内容', contentUpdated: '已更新内容', contentPublished: '已发布内容', contentUnpublished: '已取消发布内容', contentDeleted: '已删除内容', contentViewed: '已查看内容', likeAdded: '已添加点赞', likeRemoved: '已移除点赞', commentPosted: '已发布评论', commentRemoved: '已删除评论', commentRestored: '已恢复评论', profileUpdated: '已更新个人资料', siteUpdated: '已更新站点结构', thoughtsUpdated: '已更新 Thoughts 配置' }
  },
  profile: {
    pageKicker: 'Identity', pageTitle: '个人资料。', pageCopy: '公开首页展示的身份、经历和链接。', loadError: '无法加载个人资料。', saveError: '无法保存个人资料。请修正高亮字段后重试。', sectionsAria: '个人资料区块', identity: 'Identity', links: 'Links', interests: 'Interests', cv: 'CV', series: 'Series', contact: 'Contact', introduction: '简介', websiteResume: '网站与简历', background: '经历', mySeries: '我的系列', displayName: '显示名称', handle: '用户名', location: '位置', headline: '标题简介', bio: '个人简介', organization: '组织', organizationDescription: '显示在首页个人简介上方。', avatarUrl: '头像 URL', previewAvatar: '预览头像', avatarPreview: '头像预览', imageTypes: '仅接受 PNG、JPEG、WebP、GIF 和 AVIF 图片。', avatarUploadError: '头像上传失败。', websiteUrl: '网站 URL', resumeUrl: '简历 PDF URL', previewResume: '预览简历', pdfOnly: '仅接受 PDF 文件。', resumeUploadError: '简历上传失败。', tags: '标签', addInterest: '输入兴趣后按 Enter 添加', tagsHint: '在简介下以 #标签 形式呈现。', educationExperience: '教育与工作经历', backgroundSection: '经历区块', education: '教育经历', experience: '工作经历', contactLinks: '联系链接', addLink: '添加链接', addSeries: '添加系列', addEducation: '添加教育经历', addExperience: '添加工作经历', chooseIcon: '选择图标', label: '标签', url: 'URL', category: '分类', description: '描述', name: '名称', institution: '院校', program: '专业', role: '职位', period: '时间段', editPeriod: '编辑时间段', edit: '编辑', from: '开始', to: '结束', startMonth: '开始月份', endMonth: '结束月份', now: '至今', openEnded: '当前为开放时间段——选择结束月份即可结束。', leaveEmpty: '“结束”留空表示“至今”。', clearPeriod: '清除时间段', iconFallback: '将回退到地球图标——请选择图标或调整标签。', iconRenders: '首页将显示为 {{icon}}。', preview: 'Preview', yourName: '你的名字', noWebsite: '尚未填写网站 URL。', website: '网站', resume: '简历', pdfDownload: 'PDF 下载', noResume: '尚未上传简历 PDF。', noInterests: '尚未添加兴趣。', noBackground: '尚未添加教育或工作经历。', noSeries: '尚未添加系列。', noPublicLinks: '尚未添加公开链接。', locationPreview: '位置将显示为“{{location}} · UTC+8”。', saveProfile: '保存个人资料'
  },
  settings: {
    kicker: 'Configuration', title: '站点设置。', copy: '配置公开站点的身份、导航、评论和首页结构。', loadError: '无法加载站点配置。', saveError: '无法保存站点配置。请修正高亮字段后重试。', identity: 'Identity', identityTitle: '标题、描述与页脚', siteTitle: '站点标题', siteTitleDescription: '用于浏览器标题、SEO 元数据和 RSS 频道名称。', description: '描述', descriptionHelp: '{{count}}/200 · 用作默认 SEO 和 RSS 描述。', footer: '页脚文字', footerHelp: '{{count}}/200 · 显示在每个页面底部。', socialLinks: '社交链接', addSocial: '添加社交链接', navigation: 'Navigation', primaryNavigation: '主导航', addNavigation: '添加导航链接', navigationHint: '内部链接形如 /writing 或 /thoughts；外部链接使用完整 URL。', comments: 'Comments', publicDiscussions: '公开讨论', allowComments: '允许公开评论', commentsDescription: '关闭后，站点会隐藏评论表单，公开 API 会以 403 拒绝新评论。', homepage: 'Homepage', sections: '区块', homepageSections: '首页区块', save: '保存站点设置', section: { profile: '个人资料', background: '经历', recentContent: '最近内容', updates: '更新', series: '我的系列', contact: '联系' }, moveUp: '上移“{{section}}”', moveDown: '下移“{{section}}”'
  },
  agentSettings: {
    kicker: 'Agent', title: '模型与运行参数', configured: '密钥已配置', notConfigured: '密钥未配置', loadError: '无法加载 Agent 设置。', saveError: '无法保存 Agent 设置，请检查字段后重试。', provider: 'Provider', model: '模型', modelHelp: '下一次对话运行会立即使用该模型。', maxToolRounds: '最大工具回合', historyLimit: '压缩触发阈值', historyLimitHelp: '达到该未压缩消息数后，将较旧 turns 汇总为 Summary。', compactionRecentTurns: '原样保留的最近 turns', compactionRecentTurnsHelp: '压缩后仍逐条保留的最新完整 turns 数。', compactionMaxOutputTokens: 'Summary 输出 Token', compactionMaxOutputTokensHelp: '每次增量生成 Summary 的最大输出预算。', maxOutputTokens: '回答最大 Token', baseURL: 'OpenAI Base URL', baseURLHelp: '支持 OpenAI Responses API 的 HTTP(S) 基地址。', apiKey: 'OpenAI API Key', apiKeyKeep: '留空会保留当前密钥；保存后不会回显明文。', apiKeyMissing: '配置后才能运行 Agent；保存后不会回显明文。', clearAPIKey: '清除已保存的 API key', save: '保存 Agent 设置', validation: { model: '模型不能为空且不能超过 200 个字符。', toolRounds: '工具回合必须在 1 到 12 之间。', history: '压缩阈值必须在 1 到 200 条消息之间。', recentTurns: '最近 turns 必须在 1 到 99 之间。', compactionTokens: 'Summary 输出 Token 必须在 128 到 8192 之间。', compactionWindow: '原样保留的最近 turns 对当前阈值过大。', outputTokens: '回答 Token 必须在 1 到 128000 之间。', baseURL: '请输入有效的 HTTP(S) URL。' }
  },
  writings: {
    kicker: 'Writings', title: '值得反复阅读的 Writings。', copy: '呈现完整阅读体验的深度技术内容。', new: '新建 writing', pin: '置顶到 Writings 归档', pinDescription: '将此 writing 置顶到公开 Writings 页顶部的精选区域。可以置顶多个 writing。', pinError: '无法更新置顶状态。', loadError: '无法加载此 writing。请返回后重试。', titleLabel: '标题', titlePlaceholder: '给读者一个清晰承诺的标题', slug: 'Slug', slugPlaceholder: 'a-readable-url', summary: '摘要', summaryDescription: '✦ {{count}}/4000 · 显示在归档卡片上', tags: '标签', addTag: '输入标签后按 Enter 添加', language: '内容语言', languageDescription: '此 writing 使用的语言，会显示在文章元信息中', languagePlaceholder: '例如：简体中文', languagePresetOther: '其他', readingTime: '预计阅读时间', minutes: '{{count}} 分钟', recalculated: 'Core 会在保存时重新计算', aiAssisted: 'AI 辅助 writing', aiDescription: '允许读者通过“非 AI 写作”筛选掉此 writing', saveError: '无法保存此 writing。请检查字段和 Core 状态。', editorHint: '在即时渲染编辑器中写作——标题、列表、代码和数学公式会随输入格式化；图片可粘贴、拖放或从工具栏上传，并存储在 Core 中。保存值为纯 Markdown。', minRead: '阅读约 {{count}} 分钟'
  },
  thoughts: {
    kicker: 'Thoughts', title: '随时捕捉 Thoughts。', copy: '保持轻量的片段、方法和阅读笔记。', new: '新建 thought', pin: '置顶到 Thoughts 归档', pinDescription: '将此 thought 置顶到公开 Thoughts 页顶部的精选区域。可以置顶多个 thought。', pinError: '无法更新置顶状态。', loadError: '无法加载此 thought。请返回后重试。', titleLabel: '标题', optional: '可选', slug: 'Slug', slugPlaceholder: 'a-readable-url', summary: '摘要', summaryDescription: '✦ {{count}}/4000 · 显示在带 ✦ 标记的卡片上', tags: '标签', addTag: '输入标签后按 Enter 添加', provenance: 'Provenance', mood: '心境', moodDescription: '灵感 · 简短的心理状态', question: '问题', questionDescription: '渲染为反思引用块', context: '语境', contextDescription: '语境 · 它来自哪里', source: '来源', sourceDescription: '来源 · 书籍、论文或对话', saveError: '无法保存此 thought。请检查字段和 Core 状态。', editorHint: '在即时渲染编辑器中写作——图片可粘贴、拖放或从工具栏上传，并存储在 Core 中。保存值为纯 Markdown。'
  },
  media: {
    kicker: 'Media', title: '与文字并存的文件。', copy: '上传内容存储在 Core 中——图片内嵌显示，PDF 可从个人资料链接。', search: '搜索媒体', dropzoneAria: '上传图片或 PDF', dropzone: '将图片或 PDF 拖到此处，或点击上传——编辑器中也支持粘贴和拖放。', uploading: '上传中…', accepted: '仅接受 PNG、JPEG、WebP、GIF、AVIF 图片和 PDF 文件。', uploadError: '媒体上传失败。', deleteInUse: '此文件正在已发布或草稿内容中使用。请先移除相关引用。', deleteError: '无法删除媒体。', listError: '无法加载媒体列表，请重试。', open: '打开 {{filename}}', deleteNamed: '删除 {{filename}}', deleteConfirm: '删除此文件吗？引用它的位置将显示为损坏。', noMatch: '没有符合当前筛选条件的文件。', none: '尚未上传文件——可在上方拖入图片或 PDF，也可粘贴到编辑器。', back: '返回媒体', notFound: '找不到此文件，它可能已被删除。', uploadedAt: '上传于 {{date}} · {{size}}', type: '类型', size: '大小', uploaded: '上传时间', id: 'ID', usedBy: 'Used by', references: '引用', refsError: '无法加载引用列表，请重试。', noRefs: '没有已发布或草稿内容引用此文件。', untitled: '未命名 {{kind}}', openEditor: '打开编辑器', openReference: '在编辑器中打开 {{title}}', loadError: '无法加载此文件，请重试。', copyError: '无法复制 Markdown 引用。'
  },
  markdown: {
    callout: '提示块', calloutType: '{{type}}提示块', calloutTypes: { note: '备注', tip: '提示', important: '重要', warning: '警告', caution: '注意' }, footnote: '脚注', keyboard: '键盘按键', highlight: '高亮', diff: 'Diff 代码块', uploadImage: '上传图片', imageAlt: '图片', unsupportedImage: '不支持的图片类型：{{name}}', uploadFailed: '图片上传失败。', highlightPlaceholder: '高亮文字', diffAdded: '新增行', diffRemoved: '删除行', diffPlain: '普通行'
  }
} as const

export default zhCN
